Output demos/demo.gif
Set FontSize 16
Set Width 1200
Set Height 1000
Set Shell zsh
Set TypingSpeed .3s
Type "./strut-cli"
Enter
Sleep 2
Type "A really cool golang program"
Sleep 2
Enter
Sleep 10
Down 1
Sleep 1
Down 1
Sleep 1
Down 1
Sleep 1
Down 1
Sleep 1
Down 1
Sleep 1
Down 1
Sleep 1
Down 1
Sleep 2
Up 1
Sleep 1
Up 1
Sleep 1
Up 1
Sleep 1
Up 1
Sleep 2
Type "A few book recommendations"
Enter
Sleep 6
Tab
Sleep 2
Up
Sleep 2
Enter
Sleep 2
Tab
Sleep 2
Down
Sleep 2
Enter
Sleep 2
